services:
  # Backend API service
  - type: web
    name: ai-media-processor-api    
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MAX_UPLOAD_SIZE
        value: 10485760  # 10MB in bytes
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1
